---
# tasks file
# reference
# systemctl commands to start libvirt modular daemons
# https://libvirt.org/daemons.html#switching-to-modular-daemons
# network descriptions
# https://wiki.libvirt.org/VirtualNetworking.html
# virtualization on RHEL 9
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/configuring_and_managing_virtualization/index

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html
- name: Install the 'Virtualization Host' environment group and friends
  ansible.builtin.dnf:
    name:
      - '@virtualization-host-environment'
      - python3-libvirt
      - virt-install
      - cockpit
      - cockpit-machines
      - guestfs-tools  # provides virt-customize and other tools
    state: present

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html
- name: Enable libvirt's systemd socket files
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
  loop:
    - virtnetworkd-admin.socket
    - virtnetworkd-ro.socket
    - virtnetworkd.socket
    - virtnodedevd-admin.socket
    - virtnodedevd-ro.socket
    - virtnodedevd.socket
    - virtnwfilterd-admin.socket
    - virtnwfilterd-ro.socket
    - virtnwfilterd.socket
    - virtqemud-admin.socket
    - virtqemud-ro.socket
    - virtqemud.socket
    - virtsecretd-admin.socket
    - virtsecretd-ro.socket
    - virtsecretd.socket
    - virtstoraged-admin.socket
    - virtstoraged-ro.socket
    - virtstoraged.socket

- name: Enable libvirt's systemd service files
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
  loop:
    - virtnetworkd.service
    - virtnodedevd.service
    - virtnwfilterd.service
    - virtqemud.service
    - virtsecretd.service
    - virtstoraged.service

- name: Start libvirt's systemd socket files
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
  loop:
    - virtnetworkd-admin.socket
    - virtnetworkd-ro.socket
    - virtnetworkd.socket
    - virtnodedevd-admin.socket
    - virtnodedevd-ro.socket
    - virtnodedevd.socket
    - virtnwfilterd-admin.socket
    - virtnwfilterd-ro.socket
    - virtnwfilterd.socket
    - virtqemud-admin.socket
    - virtqemud-ro.socket
    - virtqemud.socket
    - virtsecretd-admin.socket
    - virtsecretd-ro.socket
    - virtsecretd.socket
    - virtstoraged-admin.socket
    - virtstoraged-ro.socket
    - virtstoraged.socket
